import React, { useMemo, useRef, useState } from "react";
import { CARDS_BY_ID } from "../game/cards.js";
import { BOARD_RADIUS, HEX_SIZE, hexCenter, hexPolygonPoints, parseHexId } from "../game/hex.js";
import modelManifest from "../game/model-manifest.json";
import { TILE_W, TILE_H, TERRAIN_TILES, sortForDepth } from "../game/iso.js";
import {
  FACILITY_COST,
  LAND_COST,
  LAND_SURCHARGE_STEP,
  MAX_UPGRADES,
  buildableHexIds,
  validFacilityHexIds,
  validLandPurchaseIds
} from "../game/logic.js";
import { PLAYER_COLORS, PLAYER_NAMES } from "../game/reducer.js";
import Card from "./Card.jsx";
import { AttractionSprite, FacilitySprite, WaterTile } from "./sprites.jsx";

const MIN_ZOOM = 0.6;
const MAX_ZOOM = 3;

// Pre-rendered 3D-model sprites drawn once across an attraction's whole
// footprint, keyed by card id. Generated by scripts/render-models.mjs; each
// manifest maps a screen angle to an image + anchor, plus the baked span.
const MODEL_SPRITES = modelManifest;

// One image drawn across all tiles of an attraction, oriented along the axis
// between its two farthest hexes and scaled to the actual placement span.
// Animated models bake their frames into one vertical sprite sheet; a
// discrete SMIL translate steps the sheet behind a one-frame clip window.
function PlacedModel({ attr, model }) {
  const centers = attr.hexes.map((id) => {
    const { q, r } = parseHexId(id);
    return hexCenter(q, r);
  });
  let ai = 0, bi = 0, best = 0;
  for (let i = 0; i < centers.length; i++) {
    for (let j = i + 1; j < centers.length; j++) {
      const d = (centers[i].x - centers[j].x) ** 2 + (centers[i].y - centers[j].y) ** 2;
      if (d > best) { best = d; ai = i; bi = j; }
    }
  }
  const a = centers[ai];
  const b = centers[bi];
  let angle =
    ai === bi ? 0 : Math.round((Math.atan2(b.y - a.y, b.x - a.x) * 180) / Math.PI / 30) * 30;
  angle = ((angle % 360) + 360) % 360;
  const m = model.sprites[angle];
  if (!m) return null;
  const k = (Math.sqrt(best) + TILE_W) / model.span; // fit the actual footprint
  const mx = (a.x + b.x) / 2;
  const my = (a.y + b.y) / 2 + HEX_SIZE * 0.45;
  const clipId = `model-clip-${attr.id}`;
  return (
    <g pointerEvents="none">
      <ellipse
        cx={mx}
        cy={my}
        rx={(model.span * (model.visualScale ?? 1) * k) / 2 - 4}
        ry={5}
        transform={`rotate(${angle} ${mx} ${my})`}
        fill="#00000022"
      />
      {m.frames ? (
        <g transform={`translate(${mx - m.ox * k}, ${my - m.oy * k}) scale(${k})`}>
          <clipPath id={clipId}>
            <rect x="0" y="0" width={m.w} height={m.h} />
          </clipPath>
          <g clipPath={`url(#${clipId})`}>
            <image href={m.file} x="0" y="0" width={m.w} height={m.h * m.frames}>
              <animateTransform
                attributeName="transform"
                type="translate"
                calcMode="discrete"
                values={Array.from({ length: m.frames }, (_, i) => `0 ${-i * m.h}`).join("; ")}
                dur={`${model.frameDur * m.frames}s`}
                repeatCount="indefinite"
              />
            </image>
          </g>
        </g>
      ) : (
        <image
          href={m.file}
          x={mx - m.ox * k}
          y={my - m.oy * k}
          width={m.w * k}
          height={m.h * k}
        />
      )}
    </g>
  );
}

export default function Board({ state, dispatch }) {
  const player = state.players.find((p) => p.id === state.currentPlayerId);
  const [hovered, setHovered] = useState(null); // { attr, x, y } for card preview
  const [view, setView] = useState({ k: 1, tx: 0, ty: 0 }); // pan/zoom
  const svgRef = useRef(null);
  const dragRef = useRef(null); // { x, y, tx, ty, moved }
  const hexesByIdMap = useMemo(
    () => Object.fromEntries(state.hexes.map((h) => [h.id, h])),
    [state.hexes]
  );

  // Highlights per selected action
  const highlightHexes = useMemo(() => {
    if (state.phase !== "playing") return new Set();
    if (state.selectedAction === "buyLand") {
      const surcharge = LAND_SURCHARGE_STEP * state.landBoughtThisTurn;
      return new Set(validLandPurchaseIds(player, hexesByIdMap, surcharge));
    }
    if (state.selectedAction === "buildAttraction" && state.selectedCardId) {
      return new Set(buildableHexIds(player, hexesByIdMap, CARDS_BY_ID[state.selectedCardId]));
    }
    if (state.selectedAction === "upgrade") {
      const upgradable = state.attractions.filter(
        (a) => a.owner === player.id && a.level < MAX_UPGRADES
      );
      return new Set(upgradable.flatMap((a) => a.hexes));
    }
    if (state.selectedAction === "buildFacility") {
      return new Set(validFacilityHexIds(player, hexesByIdMap));
    }
    return new Set();
  }, [state.phase, state.selectedAction, state.selectedCardId, state.attractions, state.landBoughtThisTurn, player, hexesByIdMap]);

  const pad = HEX_SIZE * 1.3;
  const boardRadius = state.boardRadius ?? BOARD_RADIUS;
  const w = TILE_W * (boardRadius * 2 + 1);
  const h = HEX_SIZE * 1.5 * (boardRadius * 2 + 1) + HEX_SIZE;
  const viewBox = `${-w / 2 - pad} ${-h / 2 - pad * 1.4} ${w + pad * 2} ${h + pad * 2.4}`;

  const sorted = useMemo(() => sortForDepth(state.hexes), [state.hexes]);

  // --- pan/zoom ---
  const svgPoint = (clientX, clientY) => {
    const m = svgRef.current.getScreenCTM().inverse();
    return new DOMPoint(clientX, clientY).matrixTransform(m);
  };
  const zoomAt = (px, py, factor) => {
    setView((v) => {
      const k = Math.min(MAX_ZOOM, Math.max(MIN_ZOOM, v.k * factor));
      const r = k / v.k;
      return { k, tx: px - (px - v.tx) * r, ty: py - (py - v.ty) * r };
    });
  };
  const onWheel = (e) => {
    const p = svgPoint(e.clientX, e.clientY);
    zoomAt(p.x, p.y, e.deltaY < 0 ? 1.15 : 1 / 1.15);
  };
  const onPointerDown = (e) => {
    dragRef.current = { x: e.clientX, y: e.clientY, tx: view.tx, ty: view.ty, moved: false };
  };
  const onPointerMove = (e) => {
    const d = dragRef.current;
    if (!d || e.buttons === 0) return;
    const rect = svgRef.current.getBoundingClientRect();
    const vb = svgRef.current.viewBox.baseVal;
    const f = vb.width / rect.width; // svg units per screen px
    const dx = (e.clientX - d.x) * f;
    const dy = (e.clientY - d.y) * f;
    if (Math.abs(e.clientX - d.x) + Math.abs(e.clientY - d.y) > 5) d.moved = true;
    if (d.moved) setView((v) => ({ ...v, tx: d.tx + dx, ty: d.ty + dy }));
  };
  const clickHexUnlessDragged = (hexId) => {
    if (dragRef.current?.moved) return; // was a pan, not a click
    dispatch({ type: "CLICK_HEX", hexId });
  };

  return (
    <>
    <div className="zoom-controls">
      <button title="Zoom in" onClick={() => zoomAt(0, 0, 1.25)}>＋</button>
      <button title="Zoom out" onClick={() => zoomAt(0, 0, 1 / 1.25)}>－</button>
      <button title="Reset view" onClick={() => setView({ k: 1, tx: 0, ty: 0 })}>⟲</button>
    </div>
    <svg
      ref={svgRef}
      className="board"
      viewBox={viewBox}
      onWheel={onWheel}
      onPointerDown={onPointerDown}
      onPointerMove={onPointerMove}
    >
    <g id="board-pan" transform={`translate(${view.tx}, ${view.ty}) scale(${view.k})`}>
      {/* table shadow under the whole board */}
      <ellipse cx={0} cy={h * 0.06} rx={w * 0.56} ry={h * 0.56} fill="#00000026" />

      {sorted.map((hex) => {
        const selected = state.selectedHexIds.includes(hex.id);
        const highlighted = highlightHexes.has(hex.id);
        const dimmed = state.selectedAction && !highlighted && !selected;
        const { x, y } = hexCenter(hex.q, hex.r);
        const points = hexPolygonPoints(hex.q, hex.r);
        const attr = hex.attractionId
          ? state.attractions.find((a) => a.id === hex.attractionId)
          : null;
        const isAnchor = attr && attr.hexes[0] === hex.id;
        const modelSprite = attr ? MODEL_SPRITES[attr.cardId] : null;
        // Draw the model image with the front-most hex of the footprint (the
        // one sortForDepth places last) so it overlaps rows behind correctly.
        const isModelFront =
          modelSprite &&
          attr.hexes.every((id) => {
            if (id === hex.id) return true;
            const other = parseHexId(id);
            return hex.r > other.r || (hex.r === other.r && hex.q > other.q);
          });

        return (
          <g
            key={hex.id}
            className={highlighted || selected ? "hex clickable" : "hex"}
            opacity={dimmed ? 0.55 : 1}
            onClick={() => clickHexUnlessDragged(hex.id)}
            onMouseEnter={attr ? (e) => setHovered({ attr, x: e.clientX, y: e.clientY }) : undefined}
            onMouseLeave={attr ? () => setHovered(null) : undefined}
          >
            {hex.terrain === "water" ? (
              <WaterTile points={points} />
            ) : (
              <image
                href={TERRAIN_TILES[hex.terrain]}
                x={x - TILE_W / 2}
                y={y - TILE_H / 2}
                width={TILE_W}
                height={TILE_H}
                pointerEvents="none"
              />
            )}

            {hex.owner !== null && (
              <polygon
                points={points}
                fill={PLAYER_COLORS[hex.owner]}
                opacity={0.18}
                stroke={PLAYER_COLORS[hex.owner]}
                strokeWidth={2.6}
                strokeOpacity={0.9}
                pointerEvents="none"
              />
            )}

            {highlighted && (
              <polygon points={points} className="hex-highlight" pointerEvents="none" />
            )}
            {highlighted && state.selectedAction === "buyLand" && (
              <g transform={`translate(${x}, ${y})`} pointerEvents="none">
                <circle r={9.5} fill="#f2b134" stroke="#b07d1a" strokeWidth={1.4} />
                <text y={3.5} textAnchor="middle" className="cost-label">
                  ${LAND_COST[hex.terrain] + LAND_SURCHARGE_STEP * state.landBoughtThisTurn}
                </text>
              </g>
            )}
            {highlighted && state.selectedAction === "buildFacility" && (
              <g transform={`translate(${x}, ${y})`} pointerEvents="none">
                <circle r={9.5} fill="#f2b134" stroke="#b07d1a" strokeWidth={1.4} />
                <text y={3.5} textAnchor="middle" className="cost-label">
                  ${FACILITY_COST}
                </text>
              </g>
            )}
            {selected && (
              <polygon
                points={points}
                fill="none"
                stroke="#ff9800"
                strokeWidth={4}
                pointerEvents="none"
              />
            )}

            {hex.facility && (
              <g transform={`translate(${x}, ${y + HEX_SIZE * 0.45})`} pointerEvents="none">
                <FacilitySprite type={hex.facility} />
              </g>
            )}

            {attr && isModelFront && <PlacedModel attr={attr} model={modelSprite} />}
            {attr && (
              <g transform={`translate(${x}, ${y + HEX_SIZE * 0.45})`} pointerEvents="none">
                {!modelSprite && (
                  <AttractionSprite card={CARDS_BY_ID[attr.cardId]} scale={isAnchor ? 1 : 0.66} />
                )}
                {isAnchor && attr.level > 0 && (
                  <text x={0} y={16} textAnchor="middle" className="level-label">
                    {"★".repeat(attr.level)}
                  </text>
                )}
              </g>
            )}

            {/* invisible hit area on top so clicks land anywhere on the tile */}
            <polygon points={points} fill="transparent" stroke="none" />
          </g>
        );
      })}
    </g>
    </svg>

    {/* hover: show the original card of a built attraction */}
    {hovered && (
      <div
        className="card-pop"
        style={{
          left: Math.min(hovered.x + 18, window.innerWidth - 175),
          top: Math.max(10, hovered.y - 230)
        }}
      >
        <div className="pop-owner" style={{ "--pc": PLAYER_COLORS[hovered.attr.owner] }}>
          {PLAYER_NAMES[hovered.attr.owner]}
          {hovered.attr.level > 0 && ` · Level ${"★".repeat(hovered.attr.level)}`}
        </div>
        <Card card={CARDS_BY_ID[hovered.attr.cardId]} />
      </div>
    )}
    </>
  );
}
